FROM node:12-alpine

RUN apk add --no-cache dumb-init

WORKDIR /workspace
RUN mkdir -p simple-mysql/lib && mkdir test

COPY package.json /workspace/simple-mysql

WORKDIR /workspace/simple-mysql

RUN npm install

COPY ./lib /workspace/simple-mysql/lib
COPY ./test /workspace/simple-mysql/test

ENTRYPOINT [ "dumb-init", "--" ]

CMD [ "npm", "test" ]
