FROM node:12-alpine

RUN apk add --no-cache dumb-init

WORKDIR /workspace
RUN mkdir -p mysimplemysql8/lib && mkdir test

COPY package.json /workspace/mysimplemysql8

WORKDIR /workspace/mysimplemysql8

RUN npm install

COPY ./lib /workspace/mysimplemysql8/lib
COPY ./test /workspace/mysimplemysql8/test

ENTRYPOINT [ "dumb-init", "--" ]

CMD [ "npm", "test" ]
