FROM node:12-alpine

RUN apk add --no-cache dumb-init

WORKDIR /workspace
RUN mkdir -p simple-mysql/lib

COPY ./lib /workspace/simple-mysql/lib
COPY package.json /workspace/simple-mysql
COPY ./example /workspace/example

WORKDIR /workspace/example

ENV NODE_ENV=production
RUN npm init -y && npm install ../simple-mysql

ENTRYPOINT [ "dumb-init", "--" ]

CMD [ "node", "index.js" ]